Можно ли отловить одним блоком catch сразу несколько исключений?

Раньше, чтобы обработать несколько исключений, писали несколько блоков catch:

try {}
catch (NullPointerException n) { ... }
catch (ArithmeticException t) { ... }
catch (Exception e) { ... }

Тогда выполнялся блок первого обработанного исключения и часто приходилось прибегать к дублированию кода.

В JAVA7 появилась возможность обрабатывать сразу несколько исключений в одном блоке (multi-catch). Их можно перечислить через знак ‘|’:
catch (NullPointerException | ArithmeticException e) { ... }

Важно учитывать порядок наследования, поскольку в данном случае NullPointerException и ArithmeticException являются наследниками класса Exception: 
- Если использовать несколько блоков, родительский класс должен стоять в конце.
- А в случае с multi-catch, обрабатывать исключение класса Exception вообще нельзя, иначе мы получим ошибку компиляции: Types in multi-catch must be disjoint. 
Это происходит, потому что родительский класс перекроет собой всех наследников.
